name: akar_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  curved_labeled_navigation_bar: ^2.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/icons/

  fonts:
   - family: Zawi-Black
     fonts:
       - asset: assets/fonts/Zawi-Black.ttf
   - family: Zawi-Bold
     fonts:
      - asset: assets/fonts/Zawi-Bold.ttf
   - family: Zawi-Regular
     fonts:
      - asset: assets/fonts/Zawi-Regular.ttf